<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Texto26</name>
   <tag></tag>
   <elementGuidId>00000000-0000-0000-0000-000000000000</elementGuidId>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>android.view.View</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>instance</name>
      <type>Main</type>
      <value>28</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>5.2. Usted se obliga a no utilizar la plataforma para: I. recopilar direcciones de correo electrónico u otra información de contacto de otros usuarios por medios electrónicos u otros medios con la finalidad de enviar correos electrónicos no solicitados u otras comunicaciones no solicitadas; II. usarlo de forma ilegal o de forma que pueda dañar, deshabilitar, sobrecargar o perjudicar el sitio; III. usar secuencias de comandos automatizadas para recopilar información a través del sitio o para interactuar de cualquier otro modo con los mismos; IV. cargar, publicar, transmitir, compartir, almacenar o facilitar cualquier contenido que se considere dañino, amenazante, ilegal, difamatorio, infractor, abusivo, acosador, vulgar u obsceno, fraudulento, que vulnere el derecho a la intimidad y la propia imagen, que sea malicioso o cuestionable por motivos de raza, etnia o cualquier otro; V. cargar, publicar, transmitir, compartir, almacenar o facilitar publicidades, imágenes, frases y/o fotografías que no posean las autorizaciones correspondientes; VI. registrar más de una cuenta de usuario, registrarla en nombre de otra persona o registrar una cuenta de usuario en nombre de un grupo o entidad sin la autorización correspondiente; VII. realizar manifestaciones falsas o proporcionar información falsa; VIII. cargar, publicar, transmitir, compartir, almacenar o facilitar publicidad no solicitada o no autorizada, ofrecimientos ilícitos, materiales promocionales, spam, o cualquier otro tipo de comunicaciones ilícitas; IX. cargar, publicar, transmitir, compartir, almacenar o facilitar en el sitio datos personales de cualquier tercero sin la autorización correspondiente; X. cargar, publicar, transmitir, compartir o facilitar material que contenga virus informáticos o cualquier otro código, archivo o programa informático diseñado para interrumpir, destruir o limitar la funcionalidad de cualquier software o hardware o equipo de telecomunicaciones; XI. cargar, publicar, transmitir, compartir, almacenar o facilitar contenido que constituya, incite o proporcione instrucciones para cometer delitos, que infrinja los derechos de un tercero, dé lugar responsabilidades o vulnere cualquier ley de carácter nacional o internacional; XII. cargar, publicar, transmitir, compartir, almacenar o facilitar contenido que, a criterio exclusivo de OSDE, sea cuestionable o que restrinja o impida el uso o goce del sitio por otras personas, o que pueda exponer a OSDE o a sus usuarios a daños o responsabilidades de cualquier tipo; XIII. distribuir los archivos de usuario (conforme se lo define a continuación) sin la previa autorización por escrito de OSDE; XIV. alterar o modificar ninguna parte del sitio; XV. acceder a los archivos de usuario (conforme se lo define a continuación) o a otros contenidos ofrecidos a través del sitio utilizando cualquier tecnología o medio distintos de los utilizados en el propio sitio, o cualquier otro que OSDE designe explícitamente a tal efecto; XVI. eludir, desactivar o manipular de cualquier otra forma las funciones de seguridad del sitio u otras funciones que (i) impidan o restrinjan el uso o copia de los archivos de los usuarios o de los contenidos de OSDE, o (ii) que aplique limitaciones al uso del sitio o de los contenidos que se ofrecen a través del mismo; XVII. usar el sitio para fines comerciales sin la previa autorización por escrito de OSDE. Entre los usos comerciales prohibidos se incluyen, sin limitación alguna: a. la oferta remunerada para acceso a contenidos del sitio o a cualquiera de sus prestaciones a través de este o de otro sitio con el fin principal de obtener ingresos por publicidad o suscripciones; y b. la redistribución de los servicios con el fin principal de generar ingresos a partir de una actividad empresarial sustancialmente similar o comparable a la desarrollada por OSDE, que no haya sido expresamente autorizada por OSDE por escrito; XVIII. ofrecer servicios, con fines comerciales, a los usuarios del sitio con respecto a sus archivos de usuario; XIX. cubrir u oscurecer anuncios publicitarios en cualquier página del sitio por cualquier medio; y usar el sitio y sus prestaciones en forma contraria a las leyes y reglamentaciones aplicables.</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>package</name>
      <type>Main</type>
      <value>ar.com.portalsalud.osde</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>checkable</name>
      <type>Main</type>
      <value>false</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>checked</name>
      <type>Main</type>
      <value>false</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>clickable</name>
      <type>Main</type>
      <value>false</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>enabled</name>
      <type>Main</type>
      <value>true</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>focusable</name>
      <type>Main</type>
      <value>false</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>focused</name>
      <type>Main</type>
      <value>false</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>scrollable</name>
      <type>Main</type>
      <value>false</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>long-clickable</name>
      <type>Main</type>
      <value>false</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>password</name>
      <type>Main</type>
      <value>false</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>selected</name>
      <type>Main</type>
      <value>false</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>x</name>
      <type>Main</type>
      <value>41</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>y</name>
      <type>Main</type>
      <value>1100</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>250</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>2</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//hierarchy/android.widget.FrameLayout[1]/android.widget.LinearLayout[1]/android.widget.FrameLayout[1]/android.widget.RelativeLayout[1]/android.widget.LinearLayout[2]/android.webkit.WebView[1]/android.webkit.WebView[1]/android.view.View[23]</value>
   </webElementProperties>
</WebElementEntity>
